const API=(location.port==='8000'||location.hostname==='localhost'||location.hostname==='127.0.0.1')?'http://localhost:8000/api':'/api';
const page=document.getElementById('page'),title=document.getElementById('pageTitle');
const get=async p=>{const r=await fetch(API+p);if(!r.ok)throw new Error('API error');return r.json()};
const money=n=>Number(n).toLocaleString('en-US');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openJudge(){document.getElementById('judge').classList.add('show');document.getElementById('judge').setAttribute('aria-hidden','false')}
function closeJudge(){document.getElementById('judge').classList.remove('show');document.getElementById('judge').setAttribute('aria-hidden','true')}
async function home(){title.textContent='من المعلومة إلى المعرفة الموثوقة';const d=await get('/dashboard');page.innerHTML=`
<div class="hero"><div class="card heroMain"><span class="tag">TRUST + INTELLIGENCE + IMPACT</span><h2>نحفظ <span class="gold">رحلة المعرفة</span>، لا النص وحده.</h2><p>أَثَرُهُم يبني طبقة ثقة وذكاء فوق المحتوى الموثوق: لكل قطعة معرفة هوية، مصدر، سند، إصدار، مراجعة، ثم أثر يمكن فهمه وقياسه.</p><div class="mini-proof"><span>✓ هوية رقمية</span><span>✓ سلسلة سند</span><span>✓ AI مرتبط بالمصدر</span><span>✓ مراجعة بشرية</span><span>✓ أثر يحفظ الخصوصية</span></div><div class="flow"><span>أصل</span><b>→</b><span>سند</span><b>→</b><span>تحقق</span><b>→</b><span>فهم</span><b>→</b><span>تعلم</span><b>→</b><span>أثر</span></div></div>
<div class="card score"><div class="ring"><div><strong>${d.kpis.verification_rate}%</strong><small>سلامة السجل</small></div></div><div class="score-label">مؤشر تحقق تجريبي للعرض</div><div class="proof-line"><span>المحتوى الموثق</span><b>${money(d.kpis.verified_content)}</b></div><div class="proof-line"><span>المصادر المسجلة</span><b>${money(d.kpis.trusted_sources)}</b></div><div class="notice" style="margin-top:15px;width:100%">جواز المحتوى + التحقق الفوري + المساعد الموثق + ذكاء الأثر = حل واحد.</div></div></div>
<div class="kpis">${[['محتوى موثق',d.kpis.verified_content,'سجل قابل للتحقق'],['مصدر موثوق',d.kpis.trusted_sources,'سجل مصادر'],['رحلة تعلم',d.kpis.learning_journeys,'مسارات نشطة'],['أثر مقاس',d.kpis.measured_impact,'إشارة أثر']].map(x=>`<div class="card kpi"><small>${x[0]}</small><strong>${money(x[1])}</strong><em>↗ ${x[2]}</em></div>`).join('')}</div>
<div class="section"><h3>كيف يتحول المحتوى إلى أثر؟</h3><span class="tag">Impact Intelligence</span></div><div class="card">${d.pipeline.map((x,i)=>`<div class="metric"><div><strong>${money(x.value)}</strong><small>${x.label}</small></div><div class="bar"><i style="width:${100-i*12}%"></i></div></div>`).join('')}</div>
<div class="section"><h3>ثلاثة أسباب تجعل أَثَرُهُم مختلفًا</h3></div><div class="grid"><div class="card item"><span class="tag">01 — PROVENANCE</span><h3>اعرف من أين جاء المحتوى</h3><p>هوية، مصدر، إصدار، مراجعة، وانتقال واضح بدل محتوى رقمي بلا سياق.</p></div><div class="card item"><span class="tag">02 — GROUNDED AI</span><h3>افهم دون فقد الأصل</h3><p>بحث وتلخيص وترجمة وتخصيص، مع إظهار المراجع وحدود الثقة بدل إجابة معزولة.</p></div><div class="card item"><span class="tag">03 — IMPACT</span><h3>اعرف ماذا حدث بعد الوصول</h3><p>من الوصول إلى الثقة والتعلم والتطبيق وإعادة الاستخدام، بمؤشرات مجمعة تراعي الخصوصية.</p></div></div>
<div class="feature-strip"><div class="card"><strong>01 · جواز المحتوى</strong><span>هوية رقمية وسجل زمني ومصادر مرتبطة.</span></div><div class="card"><strong>02 · بوابة الثقة</strong><span>كل إجابة ذكية قابلة للرجوع إلى أصلها.</span></div><div class="card"><strong>03 · محرك الأثر</strong><span>نقيس ما بعد المشاهدة، لا المشاهدة فقط.</span></div></div>`}
async function passport(){title.textContent='جواز المحتوى';const d=await get('/content/ATH-001');page.innerHTML=`<div class="card"><div class="section" style="margin-top:0"><div><span class="tag">${esc(d.status)} · CONTENT PASSPORT</span><h2>${esc(d.title)}</h2><p class="gold">${esc(d.topic)} · الإصدار ${esc(d.version)} · آخر تحديث ${esc(d.updated)}</p></div><button class="btn primary" onclick="runVerify('ATH-001',true)">تحقق الآن ✓</button></div><div class="grid"><div><small>Content ID</small><h3>${d.passport.content_id}</h3></div><div><small>Integrity Hash</small><h3>${d.passport.integrity_hash}…</h3></div><div><small>المراجعة</small><h3>${d.passport.reviewed_by}</h3></div></div></div>
<div class="section"><h3>سلسلة السند — من الأصل إلى النشر</h3><span class="tag">${d.sanad.length} مراحل موثقة</span></div><div class="card"><div class="sanad-graph">${d.sanad.map((s,i)=>`<div class="node"><div class="node-dot">${i===0?'أ':i===1?'✓':i===2?'↻':'أ'}</div><b>${esc(s.stage)}</b><small>${esc(s.actor)}</small></div>`).join('')}</div><div class="timeline" style="margin-top:22px">${d.sanad.map((s,i)=>`<div class="step"><div class="num">0${i+1}<br><span class="verified">✓ موثق</span></div><div><h3>${esc(s.stage)}</h3><p>${esc(s.actor)} · ${esc(s.date)} · سجل انتقال محفوظ</p></div></div>`).join('')}</div></div>
<div class="section"><h3>المصادر المرتبطة</h3><span class="tag">Source Registry</span></div><div class="grid">${d.sources.map(s=>`<div class="card item"><span class="tag">${esc(s.type)}</span><h3>${esc(s.title)}</h3><p>${esc(s.authority)} · ${esc(s.year)}</p><span class="verified">✓ ${esc(s.status)}</span></div>`).join('')}</div>`}
async function runVerify(id='ATH-001',showToast=false){try{const d=await get('/verify/'+encodeURIComponent(id));const box=document.getElementById('vres');if(box)box.innerHTML=verificationHTML(d);if(showToast)toast('تم التحقق: السجل سليم ومتكامل ✓')}catch(e){toast('تعذر الوصول إلى خدمة التحقق')}}
function verificationHTML(d){return `<div class="verification-result"><div class="seal">✓</div><div><span class="tag">VERIFIED · ${esc(d.content_id)}</span><h3 style="margin:8px 0 3px">${esc(d.message)}</h3><p style="color:var(--muted);font-size:10px;margin:0">Integrity hash: ${esc(d.integrity_hash)}</p><p style="color:var(--muted);font-size:10px;margin:5px 0 0">تم الفحص: ${new Date(d.checked_at).toLocaleString('ar-EG')}</p></div></div>`}
async function verifyPage(){title.textContent='مركز التحقق';page.innerHTML=`<div class="hero"><div class="card"><span class="tag">INSTANT VERIFICATION</span><h2>تحقق قبل أن تثق.</h2><p class="answer">أدخل هوية المحتوى أو استخدم رمز التحقق التجريبي. النظام يفحص الهوية، الإصدار، وسلامة السجل المرتبط بالمصدر.</p><div class="row"><input id="vid" class="search" value="ATH-001"><button class="btn primary" onclick="runVerify(document.getElementById('vid').value)">فحص السجل</button></div><div id="vres"></div></div><div class="card qr-wrap"><div class="qr-demo" aria-label="QR demo">${Array.from({length:81},(_,i)=>`<i class="${[0,1,2,9,18,3,10,20,7,8,15,16,17,27,35,44,53,62,71,72,73,79,80].includes(i)?'':'off'}"></i>`).join('')}</div><h3>QR · ATH-001</h3><p>رمز توضيحي لمسار التحقق السريع. في المنتج الكامل يمكن ربطه برابط التحقق العام.</p><button class="btn" onclick="document.getElementById('vid').value='ATH-001';runVerify('ATH-001',true)">محاكاة المسح ✓</button></div></div>
<div class="section"><h3>طبقات الفحص</h3></div><div class="grid"><div class="card item"><span class="tag">01</span><h3>هوية رقمية</h3><p>Content ID ثابت لكل قطعة معرفة.</p></div><div class="card item"><span class="tag">02</span><h3>سلامة الإصدار</h3><p>Hash يربط المحتوى بنسخته الحالية.</p></div><div class="card item"><span class="tag">03</span><h3>سلسلة السند</h3><p>مصدر → مراجعة → تكييف → نشر.</p></div></div>`;await runVerify('ATH-001')}
async function ai(){title.textContent='المساعد الموثق';page.innerHTML=`<div class="hero"><div class="card"><span class="tag">SOURCE-GROUNDED AI</span><h2>اسأل. وسنريك <span class="gold">المصدر</span>.</h2><input id="q" class="search" value="كيف نحافظ على أصالة المعرفة الرقمية؟"><br><br><button class="btn primary" onclick="ask()">ابحث في المصادر ✦</button><div id="ans"></div></div><div class="card"><h3>حواجز الثقة</h3><p class="answer">النظام لا يقدّم فتوى أو حكمًا مستقلًا. دوره الوصول والفهم والربط بالمصدر، بينما تبقى المراجعة العلمية البشرية شرطًا للنشر.</p><div class="notice">✓ Source-grounded<br>✓ Citations visible<br>✓ Human review gate</div></div></div>`}
async function ask(){const q=document.getElementById('q').value.trim();if(!q)return;const d=await get('/ai/answer?q='+encodeURIComponent(q));document.getElementById('ans').innerHTML=`<div class="answer"><h3>إجابة مرتبطة بالسياق</h3><p>${esc(d.answer)}</p>${d.citations.map(c=>`<span class="cite">${esc(c.title)} · ${(c.relevance*100).toFixed(0)}% صلة</span>`).join('')}<div class="notice">ثقة النموذج: ${d.confidence}% · ${esc(d.guardrail)}</div></div>`}
async function journey(){title.textContent='رحلة التعلم';const d=await get('/journey');page.innerHTML=`<div class="hero"><div class="card"><span class="tag">LEARNING JOURNEY</span><h2>${esc(d.title)}</h2><p class="answer">المحتوى لا ينتهي عند القراءة. نربطه بخطوات تحقق وفهم وتعلم وتطبيق، ثم نعيد الأثر إلى دورة التحسين.</p><div class="bar"><i style="width:${d.progress}%"></i></div><p class="gold">التقدم ${d.progress}%</p><div class="timeline">${d.steps.map(s=>`<div class="step"><div class="num">${s[0]}</div><div><h3>${esc(s[1])}</h3><p>${esc(s[2])}</p></div></div>`).join('')}</div><button class="btn primary" onclick="toast('تم تسجيل الخطوة التالية في العرض التجريبي ✓')">متابعة الرحلة →</button></div><div class="card"><span class="tag">WHY IT MATTERS</span><h3>من حفظ المعلومة إلى بناء السلوك</h3><p class="answer">كل خطوة لها وظيفة: <b>اكتشاف</b> السؤال، <b>تحقق</b> الأصل، <b>فهم</b> السياق، <b>تعلم</b> المسار، ثم <b>أثر</b> يمكن تحسينه.</p><div class="notice">الهدف ليس جمع نقرات أكثر؛ بل بناء رحلة معرفية أكثر ثقة وفائدة.</div></div></div>`}
async function impact(){title.textContent='ذكاء الأثر';const d=await get('/impact');const labels=[['الوصول',d.journey.reach],['الثقة',d.journey.trusted],['التفاعل',d.journey.engaged],['التعلم',d.journey.learned],['التطبيق',d.journey.applied],['إعادة الاستخدام',d.journey.reuse]];page.innerHTML=`<div class="hero"><div class="card"><span class="tag">IMPACT INTELLIGENCE</span><h2>السؤال ليس: كم شاهد؟<br><span class="gold">بل: ماذا حدث بعد ذلك؟</span></h2><p class="answer">هذه هي طبقة الأثر: نحول رحلة المستخدم من أرقام مشاهدة إلى إشارات ثقة وتعلم وتطبيق وإعادة استخدام، مع إبقاء البيانات مجمعة.</p></div><div class="card"><span class="tag">PRIVACY BY DESIGN</span><h3>الخصوصية جزء من المنتج</h3><p class="answer">${esc(d.privacy)}</p><span class="verified">✓ لا نحتاج كشف هوية المتعلم لقياس الاتجاهات.</span></div></div><div class="section"><h3>قمع الأثر</h3><span class="tag">Demo metrics</span></div><div class="card">${labels.map((x,i)=>`<div class="metric"><div><strong>${money(x[1])}</strong><small>${x[0]}</small></div><div class="bar"><i style="width:${Math.max(12,100-i*14)}%"></i></div></div>`).join('')}</div><div class="section"><h3>Insight Engine</h3></div><div class="grid">${d.insights.map((x,i)=>`<div class="card item"><span class="tag">Insight 0${i+1}</span><h3>${esc(x)}</h3><p>مؤشر تجريبي يحتاج اختبارًا على بيانات حقيقية قبل اعتباره نتيجة بحثية.</p></div>`).join('')}</div>`}
async function studio(){title.textContent='استوديو المعرفة';const s=await get('/sources');page.innerHTML=`<div class="hero"><div class="card"><span class="tag">HUMAN-IN-THE-LOOP</span><h2>أنشئ محتوى جديدًا <span class="gold">دون قطع السند</span>.</h2><div class="form"><label>عنوان المحتوى</label><input id="dt" class="search" value="أدب الحوار في طلب العلم"><label>الموضوع</label><input id="dp" class="search" value="التعلم"><label>المصادر المرجعية</label><div>${s.items.map(x=>`<label style="display:block;margin:7px 0;color:#d5e0db"><input type="checkbox" value="${x.id}" checked> ${esc(x.title)}</label>`).join('')}</div><button class="btn primary" onclick="draft()">توليد مسودة موثقة</button></div><div id="draft"></div></div><div class="card"><h3>بوابة النشر</h3><p class="answer">لا تتحول المسودة إلى محتوى منشور إلا بعد فحص المصادر والمراجعة البشرية. هذه ليست خطوة تجميلية؛ إنها قاعدة ثقة المنتج.</p><div class="timeline"><div class="step"><div class="num">01</div><div><h3>AI Draft</h3><p>صياغة أولية مرتبطة بالمصادر.</p></div></div><div class="step"><div class="num">02</div><div><h3>Source Check</h3><p>فحص الروابط والسياق.</p></div></div><div class="step"><div class="num">03</div><div><h3>Human Review</h3><p>مراجعة قبل النشر.</p></div></div></div></div></div>`}
async function draft(){const ids=[...document.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);const r=await fetch(API+'/studio/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:document.getElementById('dt').value,topic:document.getElementById('dp').value,source_ids:ids})});const d=await r.json();document.getElementById('draft').innerHTML=`<div class="notice" style="margin-top:18px"><b>${esc(d.draft_id)}</b> · ${esc(d.status)}<p>${esc(d.content)}</p>✓ مصادر مرتبطة &nbsp; ✓ سياق واضح &nbsp; <span class="gold">○ تنتظر المراجعة البشرية</span></div>`;toast('تم إنشاء مسودة موثقة — النشر ما زال محميًا بالمراجعة البشرية')}
const routes={home,passport,verify:verifyPage,ai,journey,impact,studio};
function go(p){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));routes[p]().catch(()=>{page.innerHTML='<div class="card empty">تعذر تحميل الصفحة. تأكد أن خدمة الـAPI تعمل.</div>'})}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeJudge()});go('home');
