const API='';
let step=0;
const titles=['What is Islam?','Who is Muhammad ﷺ?','What is the Quran?','Why do Muslims believe in One God?','How do Muslims practice Islam?'];
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
async function event(type,channel='WEB'){try{const r=await fetch(API+'/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,source_channel:channel})}); if(r.ok) toast('✓ '+type.replaceAll('_',' ').toLowerCase());}catch(e){toast('Demo event recorded locally');}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
function startExperience(){event('QR_SCANNED','DEMO');event('CONTENT_VERIFIED','DEMO');event('JOURNEY_STARTED','DEMO');refreshAll();document.getElementById('impact').scrollIntoView({behavior:'smooth',block:'start'});}
async function refreshAll(){await refresh(); await sources();}
async function refresh(){try{const d=await (await fetch(API+'/api/dashboard')).json(); for(const k of ['reach','verified','engagement','journeys','completed'])document.getElementById(k).textContent=d[k].toLocaleString();document.getElementById('floatVerified').textContent=d.verified.toLocaleString();renderFunnel(d);const ins=await (await fetch(API+'/api/insight')).json();document.getElementById('insightTitle').textContent=ins.title;document.getElementById('insight').textContent=ins.text;document.getElementById('recommendation').textContent=ins.recommendation;}catch(e){}}
function renderFunnel(d){const rows=[['Reach',d.reach,100],['Verified',d.verified,Math.max(8,d.verified/d.reach*100)],['Engaged',d.engagement,Math.max(8,d.engagement/d.reach*100)],['Journey started',d.journeys,Math.max(8,d.journeys/d.reach*100)],['Completed',d.completed,Math.max(8,d.completed/d.reach*100)]];document.getElementById('funnel').innerHTML=rows.map(r=>`<div class="funnel-row"><div><span>${r[0]}</span><b>${r[1].toLocaleString()}</b></div><div class="funnel-track"><i style="width:${Math.min(100,r[2])}%"></i></div></div>`).join('')}
function renderJourney(){document.getElementById('journey').innerHTML=titles.map((t,i)=>`<div class="journey-step ${i<step?'complete':''} ${i===step?'active':''}"><span class="step-num">${i<step?'✓':i+1}</span><div><b>${t}</b><small>${i<step?'Completed':i===step?'Current step':'Next learning step'}</small></div><span class="step-state">${i<step?'DONE':i===step?'NEXT':'—'}</span></div>`).join('');document.getElementById('progressText').textContent=`${step} / 5`;document.getElementById('progressBar').style.width=(step/5*100)+'%'}
async function completeStep(){if(step<5){step++;await event(step===1?'JOURNEY_STEP_COMPLETED':'JOURNEY_STEP_COMPLETED');if(step===5)await event('JOURNEY_COMPLETED');renderJourney();refresh();}else toast('Journey completed ✓')}
function setQuestion(q){document.getElementById('q').value=q;askAI()}
async function askAI(){const q=document.getElementById('q').value.trim();if(!q)return;const box=document.getElementById('answer');box.innerHTML='<div class="answer-loading">Retrieving from verified knowledge…</div>';try{const r=await fetch(API+'/api/ask?q='+encodeURIComponent(q));const d=await r.json();box.innerHTML=`<div class="answer-top"><span class="kicker">MATCHED TOPIC</span><b>${esc(d.matched_topic)}</b></div><p>${esc(d.answer)}</p><div class="citation"><span>⌁</span><div><b>${esc(d.citations[0].label)}</b><small>${esc(d.citations[0].content_id)} · ${esc(d.citations[0].source_id)}</small></div></div><small class="safety-note">${esc(d.safety)}</small>`;event('CONTENT_VIEWED','AI')}catch(e){box.innerHTML='<div class="error-state"><p>Unable to retrieve the demo answer.</p></div>'}}
async function sources(){try{const d=await (await fetch(API+'/api/sources')).json();document.getElementById('sourceList').innerHTML=d.items.map(s=>`<div class="source-row"><div class="source-icon">✓</div><div><b>${esc(s.id)} · ${esc(s.title)}</b><p>${esc(s.type)} · ${esc(s.language)}</p></div><span>${esc(s.verification)}</span><strong>${esc(s.license)}</strong></div>`).join('')}catch(e){}}
(async()=>{document.getElementById('qr').src=API+'/api/qr/ATHAR-2026-0001.png';renderJourney();refreshAll();if(new URLSearchParams(location.search).has('verified')){toast('✓ Content verified — continue your journey');document.getElementById('journey').scrollIntoView({behavior:'smooth'});}})();
