import os, hashlib
from datetime import datetime, timezone
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./atharhum.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg://", 1)
elif DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)

engine: Engine = create_engine(DATABASE_URL, pool_pre_ping=True, future=True)


def now(): return datetime.now(timezone.utc).isoformat()

def q(sql, params=None, many=False):
    with engine.begin() as c:
        r = c.execute(text(sql), params or {})
        return [dict(x._mapping) for x in r.fetchall()] if many else (dict(r.fetchone()._mapping) if r.fetchone() else None)

def all_rows(sql, params=None):
    with engine.connect() as c:
        return [dict(x._mapping) for x in c.execute(text(sql), params or {}).fetchall()]

def one(sql, params=None):
    with engine.connect() as c:
        x=c.execute(text(sql), params or {}).fetchone()
        return dict(x._mapping) if x else None

def execute(sql, params=None):
    with engine.begin() as c: c.execute(text(sql), params or {})

def init():
    # Portable schema. PostgreSQL gets a durable managed database on Render; local runs use SQLite.
    ddl = [
    """CREATE TABLE IF NOT EXISTS organizations (id VARCHAR(80) PRIMARY KEY, name VARCHAR(255) NOT NULL, kind VARCHAR(120), source_url TEXT NOT NULL, label VARCHAR(255) NOT NULL, country VARCHAR(120))""",
    """CREATE TABLE IF NOT EXISTS content (id VARCHAR(100) PRIMARY KEY, title TEXT NOT NULL, summary TEXT NOT NULL, organization_id VARCHAR(80) NOT NULL, source_name TEXT NOT NULL, source_url TEXT NOT NULL, license TEXT NOT NULL, rights TEXT NOT NULL, version VARCHAR(40) NOT NULL, integrity VARCHAR(128) NOT NULL, status VARCHAR(60) NOT NULL, journey_id VARCHAR(100), created_at VARCHAR(80) NOT NULL)""",
    """CREATE TABLE IF NOT EXISTS provenance (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id VARCHAR(100) NOT NULL, type VARCHAR(60), label VARCHAR(255), entity VARCHAR(255), position INTEGER NOT NULL)""",
    """CREATE TABLE IF NOT EXISTS journeys (id VARCHAR(100) PRIMARY KEY, title VARCHAR(255), content_id VARCHAR(100))""",
    """CREATE TABLE IF NOT EXISTS journey_steps (id VARCHAR(100) PRIMARY KEY, journey_id VARCHAR(100), title VARCHAR(255), description TEXT, position INTEGER NOT NULL)""",
    """CREATE TABLE IF NOT EXISTS events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type VARCHAR(80), content_id VARCHAR(100), journey_id VARCHAR(100), metadata TEXT, created_at VARCHAR(80))""",
    """CREATE TABLE IF NOT EXISTS collaborations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_id VARCHAR(100), role VARCHAR(120), note TEXT, status VARCHAR(80), created_at VARCHAR(80))""",
    ]
    # SQLite does not understand GENERATED IDENTITY.
    if engine.dialect.name == 'sqlite':
        ddl[2]=ddl[2].replace('INTEGER GENERATED BY DEFAULT AS IDENTITY','INTEGER').replace(' PRIMARY KEY',' PRIMARY KEY AUTOINCREMENT',1)
        ddl[5]=ddl[5].replace('INTEGER GENERATED BY DEFAULT AS IDENTITY','INTEGER').replace(' PRIMARY KEY',' PRIMARY KEY AUTOINCREMENT',1)
    for s in ddl: execute(s)
    seed()

def seed():
    if one("SELECT id FROM organizations LIMIT 1"): return
    orgs=[
      ("kfqc","مجمع الملك فهد لطباعة المصحف الشريف","قرآن ونشر رقمي","https://qurancomplex.gov.sa/","مؤسسة مرجعية — لا توجد شراكة مدعاة","السعودية"),
      ("ksu-ayat","مشروع المصحف الإلكتروني آيات — جامعة الملك سعود","محتوى قرآني رقمي","https://quran.ksu.edu.sa/","مؤسسة/مشروع مرجعي — لا توجد شراكة مدعاة","السعودية"),
      ("azhar-ira","مجمع البحوث الإسلامية — الأزهر الشريف","بحث ونشر إسلامي","https://azhar.eg/","مؤسسة مرجعية — لا توجد شراكة مدعاة","مصر"),
      ("ksu-press","دار جامعة الملك سعود للنشر — الدراسات الإسلامية","نشر أكاديمي إسلامي","https://direct.ksu.edu.sa/communities/b0e834c3-60c9-4d17-9b3c-9adfa306d49d/browse/dateissued","مؤسسة/منصة نشر مرجعية — لا توجد شراكة مدعاة","السعودية")]
    for o in orgs: execute("INSERT INTO organizations(id,name,kind,source_url,label,country) VALUES(:id,:name,:kind,:url,:label,:country)",dict(zip(['id','name','kind','url','label','country'],o)))
    items=[
      ("quran-ayat-001","مشروع آيات: المصحف الإلكتروني","سجل تعريفي لمورد قرآني رقمي رسمي من جامعة الملك سعود، يربط المستخدم بالمصدر الأصلي ومسار التحقق والتعلم.","ksu-ayat","مشروع المصحف الإلكتروني آيات — جامعة الملك سعود","https://quran.ksu.edu.sa/","المحتوى الأصلي يخضع لشروط الجهة والمصادر؛ أَثَرُهُم يحفظ بيانات المصدر ولا يفترض حق إعادة النشر","تحقق من الحقوق على مستوى الأصل","1.0","registered","journey-quran-001"),
      ("islamic-research-001","البحوث الإسلامية — الأزهر الشريف","بوابة مرجعية لمحتوى وبحوث ومطبوعات مرتبطة بالدراسات الإسلامية، مع تتبع الجهة الأصلية بدل نسخ المحتوى داخل أَثَرُهُم.","azhar-ira","Islamic Research Academy — Al-Azhar","https://azhar.eg/","المحتوى وحقوق النشر لدى الجهة المالكة؛ الاستخدام في أَثَرُهُم يقتصر على بيانات الفهرسة والروابط المرجعية","بيانات مصدر فقط","1.0","registered","journey-research-001"),
      ("islamic-studies-001","مجلة الدراسات الإسلامية — دار جامعة الملك سعود للنشر","سجل لمورد نشر أكاديمي في الدراسات الإسلامية، يوضح كيف يمكن تتبع الأصل والإصدار والجهة ومسار التعلم.","ksu-press","دار جامعة الملك سعود للنشر — مجلة الدراسات الإسلامية","https://direct.ksu.edu.sa/communities/b0e834c3-60c9-4d17-9b3c-9adfa306d49d/browse/dateissued","المقالة/البحث وحقوقه تخضع للناشر؛ لا يفترض السجل ترخيص إعادة الاستخدام","بيانات مصدر فقط","1.0","registered","journey-studies-001")]
    for i in items:
        vals=list(i); vals.insert(9,hashlib.sha256(i[0].encode()).hexdigest())
        execute("""INSERT INTO content(id,title,summary,organization_id,source_name,source_url,license,rights,version,integrity,status,journey_id,created_at)
        VALUES(:id,:title,:summary,:organization_id,:source_name,:source_url,:license,:rights,:version,:integrity,:status,:journey_id,:created_at)""",dict(zip(['id','title','summary','organization_id','source_name','source_url','license','rights','version','integrity','status','journey_id','created_at'], vals+[now()])))
    prov=[
      ("quran-ayat-001","source","المصدر الأصلي","مشروع آيات — جامعة الملك سعود",0),("quran-ayat-001","institution","الجهة الناشرة/المشغلة","جامعة الملك سعود",1),("quran-ayat-001","verification","سجل الهوية والتحقق","Atharhum Registry",2),("quran-ayat-001","learning","رحلة تعلم مرتبطة بالمصدر","From Source to Athar",3),
      ("islamic-research-001","source","المصدر الأصلي","مجمع البحوث الإسلامية — الأزهر",0),("islamic-research-001","institution","الجهة العلمية","الأزهر الشريف",1),("islamic-research-001","verification","سجل الهوية والتحقق","Atharhum Registry",2),("islamic-studies-001","source","المصدر الأصلي","دار جامعة الملك سعود للنشر",0),("islamic-studies-001","institution","الجهة الناشرة","جامعة الملك سعود",1),("islamic-studies-001","verification","سجل الهوية والتحقق","Atharhum Registry",2)]
    for p in prov: execute("INSERT INTO provenance(content_id,type,label,entity,position) VALUES(:content_id,:type,:label,:entity,:position)",dict(zip(['content_id','type','label','entity','position'],p)))
    journeys=[("journey-quran-001","رحلة التحقق من مصدر قرآني إلى تعلم موثوق","quran-ayat-001"),("journey-research-001","رحلة البحث الإسلامي من المؤسسة إلى الفهم","islamic-research-001"),("journey-studies-001","رحلة الباحث في الدراسات الإسلامية","islamic-studies-001")]
    for j in journeys: execute("INSERT INTO journeys(id,title,content_id) VALUES(:id,:title,:content_id)",dict(zip(['id','title','content_id'],j)))
    steps=[
      ("q1","journey-quran-001","اكتشف المصدر","ابدأ من الصفحة الأصلية للجهة، لا من نسخة مجهولة.",0),("q2","journey-quran-001","افتح الـPassport","راجع هوية السجل والجهة والإصدار والحقوق.",1),("q3","journey-quran-001","تحقق","افحص QR وهوية السجل وسلامة البيانات.",2),("q4","journey-quran-001","تتبع السند الرقمي","شاهد انتقال السجل من المصدر إلى أَثَرُهُم ثم إلى رحلة التعلم.",3),("q5","journey-quran-001","تعلم","اقرأ وافهم من خلال المصدر المرتبط، ثم سجل تقدمك.",4),("q6","journey-quran-001","اترك أثرًا","سجل إتمام الرحلة لتكوين أثر تعلم قابل للقياس.",5),
      ("r1","journey-research-001","حدد المؤسسة","تعرف على الجهة العلمية ومجالها.",0),("r2","journey-research-001","تحقق من الأصل","افتح المصدر الرسمي وسجل المرجع.",1),("r3","journey-research-001","افهم السياق","راجع نوع المادة والجهة المالكة قبل إعادة الاستخدام.",2),("r4","journey-research-001","تعلم","حوّل المصدر إلى خطوة تعلم قابلة للتتبع.",3),("r5","journey-research-001","الأثر","سجل ما أنجزته من الرحلة.",4),
      ("s1","journey-studies-001","استكشف الإصدار","ابدأ من فهرس الناشر.",0),("s2","journey-studies-001","تحقق من المصدر","تأكد من الجهة والإصدار والحقوق.",1),("s3","journey-studies-001","اقرأ بوعي","افصل بين المصدر الأصلي وأي تلخيص أو إعادة استخدام.",2),("s4","journey-studies-001","سجل الأثر","سجل إتمام الرحلة.",3)]
    for s in steps: execute("INSERT INTO journey_steps(id,journey_id,title,description,position) VALUES(:id,:journey_id,:title,:description,:position)",dict(zip(['id','journey_id','title','description','position'],s)))

init()
