import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const API='';
const get=u=>fetch(API+u).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json()});
const post=(u,b)=>fetch(API+u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json()});
function App(){
 const[tab,setTab]=useState('home'),[items,setItems]=useState([]),[orgs,setOrgs]=useState([]),[selected,setSelected]=useState('quran-ayat-001'),[pass,setPass]=useState(null),[prov,setProv]=useState(null),[verify,setVerify]=useState(null),[qr,setQr]=useState(null),[journey,setJourney]=useState(null),[impact,setImpact]=useState(null),[answer,setAnswer]=useState(null),[dash,setDash]=useState(null),[toast,setToast]=useState('');
 useEffect(()=>{Promise.all([get('/api/v1/discover'),get('/api/v1/organizations')]).then(([a,b])=>{setItems(a);setOrgs(b)}).catch(e=>setToast('تعذر الاتصال بالخدمة: '+e.message))},[]);
 const openPassport=async id=>{setSelected(id);setPass(await get('/api/v1/passports/'+id));setProv(null);setVerify(null);setQr(null);setTab('passport')};
 const verifyIt=async()=>{setVerify(await get('/api/v1/verify/'+selected));setProv(await get('/api/v1/provenance/'+selected))};
 const qrIt=async()=>setQr((await get('/api/v1/qr/'+selected)).data_url);
 const ai=async()=>{setAnswer(await post('/api/v1/ai/ask',{content_id:selected,question:'ما أصل هذه المادة وما الذي يمكنني الوثوق به فيها؟'}));setTab('ai')};
 const learn=async()=>{const j=await get('/api/v1/learning/'+pass.journey_id);setJourney(j);await post('/api/v1/learning/'+j.id+'/events',{event_type:'learning_started',metadata:{source:'passport'}});setTab('learn')};
 const complete=async()=>{await post('/api/v1/learning/'+journey.id+'/events',{event_type:'learning_completed',metadata:{steps:journey.steps.length}});setImpact(await get('/api/v1/impact/'+selected));setTab('athar')};
 const institution=async oid=>{setDash(await get('/api/v1/institution/'+oid+'/dashboard'));setTab('institution')};
 const collaborate=async()=>{await post('/api/v1/collaborations',{content_id:selected,role:'institutional-review',note:'طلب تعاون تجريبي مرتبط بسجل المحتوى والحقوق'});setToast('تم تسجيل طلب التعاون في السجل.');};
 return <div className="app"><header><button className="brand" onClick={()=>setTab('home')}><span className="mark">أ</span><span><b>أَثَرُهُم</b><small>THE DIGITAL CHAIN OF TRUST</small></span></button><nav>{[['home','اكتشف'],['passport','السند الرقمي'],['learn','رحلة التعلم'],['network','المؤسسات'],['athar','الأثر']].map(([x,y])=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{y}</button>)}</nav><button className="institutionBtn" onClick={()=>institution('ksu-ayat')}>مساحة المؤسسة</button></header>
 {toast&&<button className="toast" onClick={()=>setToast('')}>{toast} ×</button>}
 {tab==='home'&&<main><section className="hero"><div className="eyebrow">TRUST / PROVENANCE / LEARNING / IMPACT</div><h1>المعرفة لا يكفي أن تصل.<br/><em>يجب أن يصل أثرها وسندها معها.</em></h1><p>أَثَرُهُم هو طبقة رقمية تحفظ رحلة المعرفة الإسلامية من المصدر إلى السند والتحقق، ثم تحولها إلى رحلة تعلم وأثر قابل للقياس — دون ادعاء الشراكة مع أي مؤسسة.</p><div className="heroActions"><button onClick={()=>openPassport('quran-ayat-001')}>ابدأ التجربة الحية</button><button className="secondary" onClick={()=>setTab('network')}>استكشف المؤسسات</button></div><div className="chain">{['المصدر','الهوية','الحقوق','السند','التحقق','الفهم','التعلم','الأثر'].map((x,i)=><div><span>0{i+1}</span>{x}</div>)}</div></section><section className="section"><div className="sectionHead"><div><div className="eyebrow">REAL REFERENCE NETWORK</div><h2>مؤسسات ومصادر حقيقية</h2></div><p>السجلات أدناه بيانات فهرسة ومصادر عامة. لا نفترض شراكة أو ترخيص إعادة نشر.</p></div><div className="cards">{items.map(i=><article className="sourceCard" onClick={()=>openPassport(i.id)}><span className="tag">{i.country}</span><h3>{i.title}</h3><p>{i.summary}</p><footer><b>{i.organization}</b><span>فتح Passport →</span></footer></article>)}</div></section></main>}
 {tab==='passport'&&<main className="page"><div className="eyebrow">CONTENT PASSPORT / {pass?.content_id}</div><h2>{pass?.title}</h2><p className="lead">{pass?.summary}</p><div className="passportGrid"><section className="passportCard"><div className="passportTop"><span>ATHARHUM ID</span><strong>{pass?.content_id}</strong></div><div className="status"><span>●</span> سجل موثق ومربوط بمصدر رسمي</div><div className="facts"><div><small>الجهة</small><b>{pass?.issuer}</b></div><div><small>الدولة</small><b>{pass?.issuer_country}</b></div><div><small>الإصدار</small><b>v{pass?.version}</b></div><div><small>سلامة السجل</small><b>SHA-256</b></div></div><div className="hash">{pass?.integrity?.value}</div><div className="actions"><button onClick={verifyIt}>تحقق وافتح السند</button><button className="secondary" onClick={qrIt}>إظهار QR</button></div>{qr&&<div className="qrBox"><img src={qr}/><small>يمسح إلى {pass.qr_url}</small></div>}</section><section className="sideCard"><div className="eyebrow">SOURCE OF RECORD</div><h3>{pass?.source?.name}</h3><p>{pass?.rights}</p><a href={pass?.source?.url} target="_blank">فتح المصدر الرسمي ↗</a><hr/><div className="eyebrow">RIGHTS</div><p>{pass?.license}</p></section></div>{verify&&<section className="card"><div className="eyebrow">VERIFICATION RESULT</div><div className="checks">{verify.checks.map(c=><div><b>✓ {c.label}</b><small>{c.status}</small></div>)}</div></section>}{prov&&<section className="card"><div className="eyebrow">DIGITAL SANAD</div><h3>سلسلة يمكن رؤيتها، لا مجرد وعد بالثقة</h3><div className="timeline">{prov.nodes.map((n,i)=><div><span>0{i+1}</span><b>{n.label}</b><small>{n.entity}</small></div>)}</div><div className="actions"><button onClick={ai}>اسأل المساعد بالدليل</button><button className="secondary" onClick={learn}>ابدأ رحلة التعلم</button></div></section>}</main>}
 {tab==='ai'&&<main className="page"><div className="eyebrow">GROUNDED INTELLIGENCE</div><h2>الذكاء يعمل داخل السند.</h2><p className="lead">المساعد هنا لا يخترع مصدرًا. الإجابة مرتبطة بالسجل الذي فتحته، ويمكنك العودة إلى الأصل في أي وقت.</p><section className="aiCard"><div className="question">ما أصل هذه المادة وما الذي يمكنني الوثوق به فيها؟</div><p>{answer?.answer}</p><div className="evidence"><span className="eyebrow">EVIDENCE</span><a href={answer?.evidence?.[0]?.url} target="_blank">{answer?.evidence?.[0]?.source} ↗</a><small>{answer?.evidence?.[0]?.reason}</small></div><button onClick={learn}>انتقل من الفهم إلى التعلم</button></section></main>}
 {tab==='learn'&&<main className="page"><div className="eyebrow">LEARNING JOURNEY</div><h2>{journey?.title}</h2><p className="lead">كل خطوة مرتبطة بسجل ومصدر. الهدف ليس إنهاء شاشة، بل تحويل المعرفة الموثقة إلى فهم قابل للمتابعة.</p><div className="journey">{journey?.steps?.map((s,i)=><div className="step"><span>0{i+1}</span><div><b>{s.title}</b><p>{s.description}</p></div>{i<journey.steps.length-1&&<i>↓</i>}</div>)}</div><button onClick={complete}>إكمال الرحلة وتسجيل الأثر</button></main>}
 {tab==='athar'&&<main className="page"><div className="eyebrow">ATHAR / IMPACT</div><h2>من الوصول إلى أثر يمكن قراءته.</h2><p className="lead">لا نقيس المشاهدة فقط. نسجل نقاط الانتقال: تحقق، سند، سؤال، بداية تعلم، إتمام، وتعاون.</p><div className="metrics">{Object.entries(impact?.metrics||{}).map(([k,v])=><div><small>{k.replaceAll('_',' ')}</small><strong>{v}</strong></div>)}</div><section className="card"><div className="impactLine"><span>المصدر</span><b>→</b><span>الثقة</span><b>→</b><span>التعلم</span><b>→</b><span>الأثر</span></div><button onClick={()=>setTab('network')}>تحويل الأثر إلى تعاون مؤسسي</button></section></main>}
 {tab==='network'&&<main className="page"><div className="eyebrow">INSTITUTIONAL NETWORK</div><h2>تعاون يحافظ على الأصل.</h2><p className="lead">المؤسسة صاحبة المصدر، مؤسسة المراجعة، الناشر أو المترجم، والجهة التعليمية يمكن أن تعمل ضمن سجل واحد مع وضوح الأصل والحقوق.</p><div className="orgGrid">{orgs.map(o=><article className="org" onClick={()=>institution(o.id)}><span>{o.country}</span><h3>{o.name}</h3><p>{o.kind}</p><a href={o.source_url} target="_blank">المصدر الرسمي ↗</a></article>)}</div><section className="collab card"><div><div className="eyebrow">LIVE WORKFLOW</div><h3>أصل → مراجعة → تكييف → تعلم</h3><p>سجل التعاون يُحفظ كحدث مرتبط بالمحتوى، لا كمحادثة منفصلة.</p></div><button onClick={collaborate}>طلب تعاون</button></section></main>}
 {tab==='institution'&&<main className="page"><div className="eyebrow">INSTITUTION WORKSPACE</div><h2>{dash?.organization?.name}</h2><p className="lead">{dash?.organization?.label}</p><div className="metrics">{Object.entries(dash?.metrics||{}).map(([k,v])=><div><small>{k.replaceAll('_',' ')}</small><strong>{v}</strong></div>)}</div><section className="card"><div className="eyebrow">KNOWLEDGE REGISTRY</div>{dash?.content?.map(c=><div className="registry"><b>{c.title}</b><span>v{c.version}</span><small>{c.status}</small></div>)}</section><section className="card"><h3>طبقة الثقة المؤسسية</h3><p>هوية · حقوق · Passport · QR · سند · تعاون · ذكاء مؤسس على الدليل · تعلم · أثر.</p><button onClick={()=>openPassport(dash.content[0].id)}>فتح أول سجل</button></section></main>}
 <footer><b>أَثَرُهُم</b><span>Source → Trust → Learning → Athar</span><span>Built as a working product, not a mockup.</span></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
